### ISSUE TITLE
Is it possible to detect warning?

### ISSUE THREAD

**Issue by Zhen-Bo** [virejdasani/InYourFace#4]
I think this extension should support warning

**Comment by fragmentedbin** [comment]
it would not be good for css tho 😌, since we know like bootstrap there is will be always some warning comes up..

**Comment by Zhen-Bo** [comment]
Maybe warning count can only activate when you using specific language that user setup at settings.json?

**Comment by fragmentedbin** [comment]
> Maybe warning count can only activate when you using specific language that user setup at settings.json?

yup would be great

**Comment by edris6** [comment]
Here: https://github.com/virejdasani/InYourFace/pull/11

**Comment by Zhen-Bo** [comment]
👍
