### ISSUE TITLE
Resize "face" to fit containing box

### ISSUE THREAD

**Issue by bennycode** [virejdasani/InYourFace#6]
I sometimes use a high zoom level in VS Code (when recording screencasts) and noticed that the Doomguy then doesn't fit it the "In your Face" box anymore. 

It would be nice if the Doomguy face would be scaled so it fits the container. Maybe the [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) property can help here as it supports a `contain` mode.

## Screenshot

![image](https://user-images.githubusercontent.com/469989/201536806-773afb3d-1347-4711-9adf-a77324407431.png)

**Comment by nqbao47** [comment]
@bennycode Hi ! Can I work on this issue? Is your problem solved yet?

**Comment by bennycode** [comment]
No, the problem still exists. Would be super nice if you could submit a PR! 😀

**Comment by virejdasani** [comment]
Fixed! New release out soon.
